micronaut:
  application:
    name: ${project.artifactId}
  caches:
    contexts:
      # allow 100 contexts to be cached
      maximum-size: 100

  metrics:
    enabled: true
    export:
      prometheus:
        step: PT2s
        descriptions: false

  multitenancy:
    tenantresolver:
      httpheader:
        enabled: true
        header-name: NGSILD-Tenant

---
endpoints:
  metrics:
    enabled: true
  health:
    enabled: true

---
datasources:
  default:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${datasources.default.host:localhost}:${datasources.default.port:5432}/${datasources.default.database}
    dialect: org.hibernate.dialect.PostgreSQL95Dialect
    database: orion
    username: orion
    password: orion

---
jpa:
  default:
    entity-scan:
      packages:
        - org.fiware.mintaka.persistence
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        # set to true if you want to see the queries.
        show_sql: false

loggers:
  level:
    root: ERROR
    org:
      fiware:
        mintaka:
          persistence: WARN
