openapi: 3.0.3
info:
  description: >-
    This OAS file describes the NGSI-LD API defined by the ETSI ISG CIM group.
    This Cross-domain Context Information Management API allows to provide,
    consume and subscribe to context information in multiple scenarios and
    involving multiple stakeholders
  version: latest
  title: ETSI ISG CIM / NGSI-LD API
  contact:
    email: NGSI-LD@etsi.org
externalDocs:
  description: Find out more about the ETSI ISG Context Information Management
  url: 'https://portal.etsi.org/tb.aspx?tbid=854&SubTB=854'
tags:
  - name: ETSI
    description: European Telecommunications Standards Institute
    externalDocs:
      description: Find out more
      url: 'http://www.etsi.org'
  - name: CIM
    description: Context Information Management
    externalDocs:
      description: Find out more
      url: 'https://portal.etsi.org/tb.aspx?tbid=854&SubTB=854'
  - name: JSON-LD
    description: JSON for Linked Data
    externalDocs:
      description: Find out more
      url: 'https://json-ld.org/'
  - name: NGSI-LD API
    description: API defined by the ETSI ISG CIM
    externalDocs:
      description: Preliminary Specification
      url: >-
        http://www.etsi.org/deliver/etsi_gs/CIM/001_099/004/01.01.01_60/gs_CIM004v010101p.pdf
paths:
  /temporal/entities/:
    get:
      description: Query temporal evolution of Entities from an NGSI-LD system
      operationId: queryTemporalEntities
      tags:
        - Temporal Evolution
      parameters:
        - $ref: '#/components/parameters/id'
        - $ref: '#/components/parameters/idPattern'
        - $ref: '#/components/parameters/type'
        - $ref: '#/components/parameters/attrs'
        - $ref: '#/components/parameters/q'
        - $ref: '#/components/parameters/georel'
        - $ref: '#/components/parameters/geometry'
        - $ref: '#/components/parameters/coordinates'
        - $ref: '#/components/parameters/geoproperty'
        - $ref: '#/components/parameters/timerel'
        - $ref: '#/components/parameters/timeproperty'
        - $ref: '#/components/parameters/time'
        - $ref: '#/components/parameters/endTime'
        - $ref: '#/components/parameters/csf'
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/components-parameters-options'
        - $ref: '#/components/parameters/lastN'
      responses:
        '200':
          description: OK
          content:
            application/json;application/ld+json:
              schema:
                $ref: '#/components/schemas/EntityTemporalList'
              examples:
                simple:
                  externalValue: >-
                    https://forge.etsi.org/rep/NGSI-LD/NGSI-LD/raw/master/examples/EntityTemporalList-example.json
        '400':
          description: Bad request
          content:
            application/json;application/ld+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
  '/temporal/entities/{entityId}':
    get:
      description: >-
        Retrieve the temporal representation of an specific Entity from an
        NGSI-LD system. It's possible to specify the Entity attributes to be
        retrieved by using query parameters
      operationId: retrieveEntityTemporalById
      tags:
        - Temporal Evolution
      parameters:
        - $ref: '#/components/parameters/entityId'
        - $ref: '#/components/parameters/attrs'
        - $ref: '#/components/parameters/parameters-type'
        - $ref: '#/components/parameters/components-parameters-options'
        - $ref: '#/components/parameters/timerel'
        - $ref: '#/components/parameters/timeproperty'
        - $ref: '#/components/parameters/time'
        - $ref: '#/components/parameters/endTime'
        - $ref: '#/components/parameters/lastN'
      responses:
        '200':
          description: OK
          content:
            application/json;application/ld+json:
              schema:
                $ref: '#/components/schemas/EntityTemporal'
              examples:
                simple:
                  externalValue: >-
                    https://forge.etsi.org/rep/NGSI-LD/NGSI-LD/raw/master/examples/EntityTemporal-example_C5.5.3.json
        '400':
          description: Bad request
          content:
            application/json;application/ld+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '404':
          description: Not Found
          content:
            application/json;application/ld+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
components:
  parameters:
    id:
      name: id
      description: Comma separated list of URIs to be retrieved
      in: query
      required: false
      schema:
        type: string
        format: uri
    idPattern:
      name: idPattern
      description: Regular expression that must be matched by Entity ids
      in: query
      required: false
      schema:
        type: string
        format: regexp
    type:
      name: type
      description: Comma separated list of Entity type names to be retrieved
      in: query
      required: false
      schema:
        type: string
    attrs:
      name: attrs
      description: >-
        Comma separated list of attribute names (properties or relationships) to
        be retrieved
      in: query
      required: false
      schema:
        type: string
    q:
      name: q
      description: Query
      in: query
      required: false
      schema:
        type: string
    georel:
      name: georel
      description: Geo-relationship
      in: query
      required: false
      schema:
        $ref: '#/components/schemas/georel'
    geometry:
      name: geometry
      description: Geometry
      in: query
      required: false
      schema:
        $ref: '#/components/schemas/geometry'
    coordinates:
      name: coordinates
      description: Coordinates serialized as a string
      in: query
      required: false
      schema:
        $ref: '#/components/schemas/coordinates'
    geoproperty:
      name: geoproperty
      description: >-
        The name of the property that contains the geo-spatial data that will be
        used to resolve the geoquery
      in: query
      required: false
      schema:
        type: string
    csf:
      name: csf
      description: Context Source Filter
      in: query
      required: false
      schema:
        type: string
    limit:
      name: limit
      description: Pagination limit
      in: query
      required: false
      schema:
        type: integer
        minimum: 1
    options:
      name: options
      description: Options dictionary
      in: query
      required: false
      schema:
        type: string
        enum:
          - keyValues
          - sysAttrs
    entityId:
      name: entityId
      description: Entity Id
      in: path
      required: true
      schema:
        type: string
        format: uri
    parameters-type:
      name: type
      description: Entity Type
      in: query
      required: false
      schema:
        $ref: '#/components/schemas/Name'
    parameters-options:
      name: options
      description: Indicates that no attribute overwrite shall be performed
      in: query
      required: false
      schema:
        type: string
        enum:
          - noOverwrite
    attrId:
      name: attrId
      description: Attribute Id
      in: path
      required: true
      schema:
        $ref: '#/components/schemas/Name'
    timerel:
      name: timerel
      description: Time relationship
      in: query
      required: false
      schema:
        $ref: '#/components/schemas/timerel'
    timeproperty:
      name: timeproperty
      description: >-
        The name of the property that contains the temporal data that will be
        used to resolve the temporal query
      in: query
      required: false
      schema:
        $ref: '#/components/schemas/Name'
    time:
      name: time
      description: start time for temporal query
      in: query
      required: false
      schema:
        type: string
        format: date-time
    endTime:
      name: endTime
      description: end time for temporal query
      in: query
      required: false
      schema:
        type: string
        format: date-time
    components-parameters-options:
      name: options
      description: Options dictionary
      in: query
      required: false
      schema:
        type: string
        enum:
          - temporalValues
          - sysAttrs
    lastN:
      name: lastN
      description: Only retrieve last N instances
      in: query
      required: false
      schema:
        type: integer
        minimum: 1
    instanceId:
      name: instanceId
      description: Instance Id
      in: path
      required: true
      schema:
        type: string
        format: uri
  schemas:
    georel:
      oneOf:
        - type: string
          enum:
            - equals
            - disjoint
            - intersects
            - within
            - contains
            - overlaps
        - type: string
          pattern: ^near;((maxDistance==\d+)|(minDistance==\d+))$
    geometry:
      type: string
      enum:
        - Point
        - MultiPoint
        - LineString
        - MultiLineString
        - Polygon
        - MultiPolygon
    position:
      description: A single position
      type: array
      minItems: 2
      maxItems: 2
      items:
        type: number
    positionArray:
      description: An array of positions
      type: array
      items:
        $ref: '#/components/schemas/position'
    lineString:
      description: An array of two or more positions
      allOf:
        - $ref: '#/components/schemas/positionArray'
        - minItems: 2
    linearRing:
      description: An array of four positions where the first equals the last
      allOf:
        - $ref: '#/components/schemas/positionArray'
        - minItems: 4
    polygon:
      description: An array of linear rings
      type: array
      items:
        $ref: '#/components/schemas/linearRing'
    coordinates:
      oneOf:
        - $ref: '#/components/schemas/position'
        - $ref: '#/components/schemas/positionArray'
        - $ref: '#/components/schemas/lineString'
        - $ref: '#/components/schemas/polygon'
    LdContext:
      oneOf:
        - type: object
        - type: string
          format: uri
        - type: array
          minItems: 1
          items:
            oneOf:
              - type: string
                format: uri
              - type: object
    observedAt:
      type: string
      format: date-time
    createdAt:
      type: string
      format: date-time
    modifiedAt:
      type: string
      format: date-time
    datasetId:
      type: string
      format: uri
    instanceId:
      type: string
      format: uri
    Property:
      type: object
      properties:
        type:
          type: string
          enum:
            - string
            - number
            - boolean
            - array
            - object
        observedAt:
          $ref: '#/components/schemas/observedAt'
        createdAt:
          $ref: '#/components/schemas/createdAt'
        modifiedAt:
          $ref: '#/components/schemas/modifiedAt'
        datasetId:
          $ref: '#/components/schemas/datasetId'
        instanceId:
          $ref: '#/components/schemas/instanceId'
      required:
        - type
        - value
      additionalProperties:
        oneOf:
          - $ref: '#/components/schemas/Property'
          - $ref: '#/components/schemas/Relationship'
    GeometrySchema:
      oneOf:
        - $ref: '#/components/schemas/position'
        - $ref: '#/components/schemas/positionArray'
        - $ref: '#/components/schemas/lineString'
        - $ref: '#/components/schemas/linearRing'
        - $ref: '#/components/schemas/polygon'

    Relationship:
      type: object
      properties:
        type:
          type: string
          enum: ["Relationship"]
        object:
          type: string
          format: uri
        observedAt:
          $ref: '#/components/schemas/observedAt'
        createdAt:
          $ref: '#/components/schemas/createdAt'
        modifiedAt:
          $ref: '#/components/schemas/modifiedAt'
        datasetId:
          $ref: '#/components/schemas/datasetId'
        instanceId:
          $ref: '#/components/schemas/instanceId'
      required:
        - type
        - object
      additionalProperties:
        oneOf:
          - $ref: '#/components/schemas/Property'
          - $ref: '#/components/schemas/Relationship'
    GeoProperty:
      type: object
      properties:
        type:
          type: string
          enum: ["GeoProperty"]
        value:
          $ref: '#/components/schemas/geometry-schema'
        observedAt:
          $ref: '#/components/schemas/observedAt'
        createdAt:
          $ref: '#/components/schemas/createdAt'
        modifiedAt:
          $ref: '#/components/schemas/modifiedAt'
        datasetId:
          $ref: '#/components/schemas/datasetId'
        instanceId:
          $ref: '#/components/schemas/instanceId'
      required:
        - type
        - value
      additionalProperties:
        oneOf:
          - $ref: '#/components/schemas/Property'
          - $ref: '#/components/schemas/Relationship'
    Name:
      type: string
      pattern: '^((\d|[a-zA-Z]|_)+(:(\d|[a-zA-Z]|_)+)?(#\d+)?)$'
      description: NGSI-LD Name
    EntityFragment:
      type: object
      properties:
        '@context':
          $ref: '#/components/schemas/LdContext'
        id:
          type: string
          format: uri
        type:
          $ref: '#/components/schemas/Name'
        createdAt:
          $ref: '#/components/schemas/createdAt'
        modifiedAt:
          $ref: '#/components/schemas/modifiedAt'
      additionalProperties:
        oneOf:
          - $ref: '#/components/schemas/Property'
          - $ref: '#/components/schemas/Relationship'
          - $ref: '#/components/schemas/GeoProperty'
    Entity:
      allOf:
        - required:
            - id
            - type
        - $ref: '#/components/schemas/EntityFragment'
    EntityList:
      type: array
      items:
        $ref: '#/components/schemas/Entity'
    ProblemDetails:
      type: object
      properties:
        type:
          type: string
          format: uri
        title:
          type: string
        detail:
          type: string
      required:
        - type
    timerel:
      type: string
      enum:
        - before
        - after
        - between
    EntityTemporalList:
      type: array
      items:
        $ref: '#/components/schemas/EntityTemporal'
    EntityTemporalFragment:
      type: object
      properties:
        '@context':
          $ref: '#/components/schemas/LdContext'
        location:
          type: array
          items:
            $ref: '#/components/schemas/GeoProperty'
          minItems: 1
        observationSpace:
          type: array
          items:
            $ref: '#/components/schemas/GeoProperty'
          minItems: 1
        operationSpace:
          type: array
          items:
            $ref: '#/components/schemas/GeoProperty'
          minItems: 1
        id:
          type: string
          format: uri
        type:
          $ref: '#/components/schemas/Name'
        createdAt:
          $ref: '#/components/schemas/createdAt'
        modifiedAt:
          $ref: '#/components/schemas/modifiedAt'
      additionalProperties:
        oneOf:
          - type: array
            items:
              $ref: '#/components/schemas/Property'
            minItems: 1
          - type: array
            items:
              $ref: '#/components/schemas/Relationship'
            minItems: 1
          - type: array
            items:
              $ref: '#/components/schemas/GeoProperty'
            minItems: 1
    EntityTemporal:
      type: object
      allOf:
        - $ref: '#/components/schemas/EntityTemporalFragment'
      required:
        - id
        - type