openapi: 3.0.3
info:
  description: 'This OAS file describes the NGSI-LD API defined by the ETSI ISG CIM group. This Cross-domain Context Information Management API allows to provide, consume and subscribe to context information in multiple scenarios and involving multiple stakeholders'
  version: latest
  title: ETSI ISG CIM / NGSI-LD API
  contact:
    email: NGSI-LD@etsi.org
externalDocs:
  description: Find out more about the ETSI ISG Context Information Management
  url: 'https://portal.etsi.org/tb.aspx?tbid=854&SubTB=854'
tags:
  - name: ETSI
    description: European Telecommunications Standards Institute
    externalDocs:
      description: Find out more
      url: 'http://www.etsi.org'
  - name: CIM
    description: Context Information Management
    externalDocs:
      description: Find out more
      url: 'https://portal.etsi.org/tb.aspx?tbid=854&SubTB=854'
  - name: JSON-LD
    description: JSON for Linked Data
    externalDocs:
      description: Find out more
      url: 'https://json-ld.org/'
  - name: NGSI-LD API
    description: API defined by the ETSI ISG CIM
    externalDocs:
      description: Preliminary Specification
      url: 'http://www.etsi.org/deliver/etsi_gs/CIM/001_099/004/01.01.01_60/gs_CIM004v010101p.pdf'
paths:
  /entities/:
    $ref: 'https://forge.etsi.org/rep/NGSI-LD/NGSI-LD/raw/master/spec/updated/entities-spec.json#/paths/%2Fentities%2F'
  '/entities/{entityId}':
    $ref: 'https://forge.etsi.org/rep/NGSI-LD/NGSI-LD/raw/master/spec/updated/entity-by-id-spec.json#/paths/%2Fentities%2F%7BentityId%7D'
  '/entities/{entityId}/attrs/':
    $ref: 'https://forge.etsi.org/rep/NGSI-LD/NGSI-LD/raw/master/spec/updated/entity-attrs-spec.json#/paths/%2Fentities%2F%7BentityId%7D%2Fattrs%2F'
  '/entities/{entityId}/attrs/{attrId}':
    $ref: 'https://forge.etsi.org/rep/NGSI-LD/NGSI-LD/raw/master/spec/updated/entity-attrs-spec.json#/paths/%2Fentities%2F%7BentityId%7D%2Fattrs%2F%7BattrId%7D'
  /temporal/entities/:
    $ref: 'https://forge.etsi.org/rep/NGSI-LD/NGSI-LD/raw/master/spec/updated/temporal/temporal-entities-spec.json#/paths/%2Ftemporal%2Fentities%2F'
  '/temporal/entities/{entityId}':
    $ref: 'https://forge.etsi.org/rep/NGSI-LD/NGSI-LD/raw/master/spec/updated/temporal/temporal-entity-by-id-spec.json#/paths/%2Ftemporal%2Fentities%2F%7BentityId%7D'
  '/temporal/entities/{entityId}/attrs/':
    $ref: 'https://forge.etsi.org/rep/NGSI-LD/NGSI-LD/raw/master/spec/updated/temporal/temporal-entity-attrs-spec.json#/paths/%2Ftemporal%2Fentities%2F%7BentityId%7D%2Fattrs%2F'
  '/temporal/entities/{entityId}/attrs/{attrId}':
    $ref: 'https://forge.etsi.org/rep/NGSI-LD/NGSI-LD/raw/master/spec/updated/temporal/temporal-entity-attrs-spec.json#/paths/%2Ftemporal%2Fentities%2F%7BentityId%7D%2Fattrs%2F%7BattrId%7D'
  '/temporal/entities/{entityId}/attrs/{attrId}/{instanceId}':
    $ref: 'https://forge.etsi.org/rep/NGSI-LD/NGSI-LD/raw/master/spec/updated/temporal/temporal-entity-attrs-spec.json#/paths/%2Ftemporal%2Fentities%2F%7BentityId%7D%2Fattrs%2F%7BattrId%7D%2F%7BinstanceId%7D'
