name: Check PR

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: jdk

      - id: bump
        uses: shioyang/check-pr-labels-on-push-action@v1.0.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labels: '["major", "minor", "patch"]'

      - uses: zwaldowski/semver-release-action@v2
        with:
          dry_run: true
          bump: ${{ steps.bump.outputs.result }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

  comment:
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: technote-space/workflow-conclusion-action@v2
      - name: Checkout
        uses: actions/checkout@v1

      - name: Comment PR
        if: env.WORKFLOW_CONCLUSION == 'failure'
        uses: thollander/actions-comment-pull-request@master
        with:
          message: "Please apply one of the following labels to the PR: 'patch', 'minor', 'major'. For more information see: https://github.com/FIWARE/mintaka/doc/CONTRIBUTING.md"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
