name: Matrix compat

on:
  push:

jobs:
  create-version-matrix:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - id: mintaka-version
        uses: wistefan/get-releases-by-pattern@master
        with:
          include: "MINOR"
          repository: fiware/mintaka


      - id: orion-version
        uses: wistefan/get-releases-by-pattern@master
        with:
          include: "MINOR"
          minMinor: "6"
          versionField: "TAG-NAME"
          repository: fiware/context.Orion-LD

    outputs:
      - mintaka-matrix: ['0.3.9', '0.2.1', '0.1.1', '0.0.12']
      - orion-matrix: ['0.7.0']

  test-compatibility:
    needs: create-version-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        orion: ${{ needs.create-version-matrix.outputs.orion-matrix }}
        mintaka: ${{ needs.create-version-matrix.outputs.mintaka-matrix }}
    steps:
      - name: test print
        run: |
            echo "${{ matrix.orion }} - ${{ matrix.mintaka}}"


