name: Matrix compat

on:
  push:

jobs:
  create-version-matrix:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - id: mintaka-version
        uses: wistefan/get-releases-by-semver@master
        with:
          include: "MINOR"
          repository: fiware/mintaka


      - id: orion-version
        uses: wistefan/get-releases-by-semver@master
        with:
          include: "MINOR"
          minMinor: "6"
          versionField: "TAG-NAME"
          repository: fiware/context.Orion-LD

    outputs:
      mintaka-matrix: ${{ steps.mintaka-version.outputs.releases }}
      orion-matrix: ${{ steps.orion-version.outputs.releases }}

  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy to disk
        run:
          cp doc/compatibility/compatibility.json /github/home/compatibility.json

  test-compatibility:
    needs: create-version-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        orion: ${{fromJson(needs.create-version-matrix.outputs.orion-matrix)}}
        mintaka: ${{fromJson(needs.create-version-matrix.outputs.mintaka-matrix)}}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ matrix.mintaka }}

      - name: Copy to disk
        run:
          cp /github/home/compatibility.json doc/compatibility/compatibility.json

      - uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: jdk

      - uses: wistefan/check-compatibility@master
        id: check-compatibility
        continue-on-error: true
        with:
          componentOne: "orion"
          componentTwo: "mintaka"
          versionOne: ${{ matrix.orion }}
          versionTwo: ${{ matrix.mintaka }}
          compatibilityFile: doc/compatibility/compatibility.json

      - name: Run tests
        id: runTest
        if: steps.check-compatibility.outcome == 'failure'
        continue-on-error: true
        run: mvn clean test
        env:
          ORION_IMAGE: fiware/orion-ld:${{ matrix.orion }}

      - name: Publish success
        if: steps.runTest.outcome == 'success'
        uses: wistefan/check-compatibility@master
        with:
          operation: "PERSIST_INFO"
          componentOne: "orion"
          componentTwo: "mintaka"
          versionOne: ${{ matrix.orion }}
          versionTwo: ${{ matrix.mintaka }}
          compatibilityFile: compatibility.json
          compatible: "True"


      - name: Publish failure
        if: steps.runTest.outcome == 'failure'
        uses: wistefan/check-compatibility@master
        with:
          operation: "PERSIST_INFO"
          componentOne: "orion"
          componentTwo: "mintaka"
          versionOne: ${{ matrix.orion }}
          versionTwo: ${{ matrix.mintaka }}
          compatibilityFile: compatibility.json
          compatible: "False"

  publish-result:
    needs:  test-compatibility
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - id: cache-json
        uses: actions/cache@v2
        with:
          path: doc/compatibility/compatibility.json
          key: json-cache

      - run: |
          ls -R

      - run: |
          cat doc/compatibility/compatibility.json
