name: Matrix compat

on:
  push:

jobs:
  create-version-matrix:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - id: mintaka-version
        uses: wistefan/get-releases-by-semver@master
        with:
          include: "MINOR"
          repository: fiware/mintaka


      - id: orion-version
        uses: wistefan/get-releases-by-semver@master
        with:
          include: "MINOR"
          minMinor: "6"
          versionField: "TAG-NAME"
          repository: fiware/context.Orion-LD

    outputs:
      mintaka-matrix: ${{ steps.mintaka-version.outputs.releases }}
      orion-matrix: ${{ steps.orion-version.outputs.releases }}

  test-compatibility:
    needs: create-version-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        orion: ${{fromJson(needs.create-version-matrix.outputs.orion-matrix)}}
        mintaka: ${{fromJson(needs.create-version-matrix.outputs.mintaka-matrix)}}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ matrix.mintaka }}

      - uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: jdk

      - uses: wistefan/check-compatibility@master
        id: check-compatibility
        continue-on-error: true
        with:
          componentOne: "orion"
          componentTwo: "mintaka"
          versionOne: ${{ matrix.orion }}
          versionTwo: ${{ matrix.mintaka }}
          compatibilityFile: doc/compatibility/compatibility.json


      - name: Run tests
        id: runTest
        if: steps.check-compatibility.outcome == 'failure'
        continue-on-error: true
        run: mvn clean test
        env:
          ORION_IMAGE: fiware/orion-ld:${{ matrix.orion }}

      - name: Publish success
        uses: wistefan/check-compatibility@master
        with:
          componentOne: "orion"
          componentTwo: "mintaka"
          versionOne: ${{ matrix.orion }}
          versionTwo: ${{ matrix.mintaka }}
          compatibilityFile: doc/compatibility/compatibility.json
          compatible: True


      - name: Publish failure
        if: steps.runTest.outcome == 'failure'
        uses: wistefan/check-compatibility@master
        with:
          componentOne: "orion"
          componentTwo: "mintaka"
          versionOne: ${{ matrix.orion }}
          versionTwo: ${{ matrix.mintaka }}
          compatibilityFile: doc/compatibility/compatibility.json
          compatible: False

      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: compatibility.json
          path: doc/compatibility/compatibility.json

  publish-result:
    needs:  test-compatibility
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2

      - run: |
          ls -R
