name: Matrix compat

on:
  push:

jobs:
  create-version-matrix:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - id: mintaka-version
        uses: wistefan/get-releases-by-pattern@master
        with:
          include: "MINOR"
          repository: fiware/mintaka


      - id: orion-version
        uses: wistefan/get-releases-by-pattern@master
        with:
          include: "MINOR"
          minMinor: "6"
          versionField: "TAG-NAME"
          repository: fiware/context.Orion-LD

    outputs:
      mintaka-matrix: ${{ steps.mintaka-version.outputs.releases }}
      orion-matrix: ${{ steps.orion-version.outputs.releases }}

  test-compatibility:
    needs: create-version-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        orion: ${{fromJson(needs.create-version-matrix.outputs.orion-matrix)}}
        mintaka: ${{fromJson(needs.create-version-matrix.outputs.mintaka-matrix)}}
    steps:
      - name: test print
        run: |
            echo "${{ matrix.orion }} - ${{ matrix.mintaka}}"


