name: Release

on:
  push:
    branches:
      - main

jobs:
  update-dockerhub-info:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: meeDamian/sync-readme@v1.0.6
        with:
          user: ${{ secrets.FIWAREBOT_USERNAME }}
          pass: ${{ secrets.FIWAREBOT_PASSWORD }}
          slug: fiware/mintaka
          readme: ./docker/description.md

  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: jdk
      
      - id: pr
        uses: actions-ecosystem/action-get-merged-pull-request@v1.0.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: zwaldowski/semver-release-action@v2
        with:
          dry_run: true
          bump: ${{ steps.pr.outputs.labels }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build image
        run: |
          mvn versions:set -DnewVersion=${VERSION}
          mvn clean install deploy -Pdocker -DskipTests -Dimage.tag=${VERSION} -Drhel.username='${{ secrets.RHEL_USERNAME }}' -Drhel.password='${{ secrets.RHEL_PASSWORD }}'

      - name: Set version output
        id: out
        run: echo "::set-output name=version::$(echo $VERSION)"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ steps.out.outputs.version }}
          prerelease: false
          title: ${{ steps.out.outputs.version }}
          files: |
            LICENSE.txt
            *.jar