name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - id: orion-version
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: fiware
          repo: context.Orion-LD
          excludes: prerelease, draft

      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: jdk

      - name: Run tests
        run: mvn clean test coveralls:jacoco -Dcoveralls.token=${{ secrets.COVERALLS_TOKEN }}
        env:
          ORION_IMAGE=fiware/orion-ld:${{ steps.orion-version.outputs.release }}